### ISSUE TITLE
Make y-axis labels horizontal

### ISSUE THREAD

**Issue by ccwang002** [jokergoo/gtrellis#3]
I was wondering if it is possible to have horizontal y labels (`track_ylab`). I have around 50 samples in their own track, and since each track height is small, the sample labels currently overlap each other a great bit.

Thanks for making this great package.

**Comment by jokergoo** [comment]
Hi, I just updated the package. You can set `ylab_rot = 0` in `gtrellis_layout()` function now.

**Comment by ccwang002** [comment]
Thanks for your prompt reply and your time working on this! I just installed the master branch version of gtrellis can confirm that the y labels are now horizontal with `ylab_rot = 0`. Thanks again!
