### ISSUE TITLE
Add row annotation and dendrogram to heatmap track

### ISSUE THREAD

**Issue by ccwang002** [jokergoo/gtrellis#4]
I was trying to make a single cell CNV heatmap similar to [this inferCNV figure](https://github.com/broadinstitute/infercnv/wiki) attached below (the bottom panel in particular), which is a trellis plot with row annotation and row dendrogram.

I was wondering if it's possible to plot it using gtrellis. Would it possible to create a grid space for a ComplexHeatmap object aligned to the gtrellis plotting space (so to add the row annotation and dendrogram)?

Sorry for this broadly open question. Any suggestion or advice is highly appreciated. Thank you!

![image](https://user-images.githubusercontent.com/1544283/97196198-32c2ac80-177a-11eb-87d5-44edc1930554.png)

**Comment by jokergoo** [comment]
Nice suggestion! I will definitely consider it! 

Thanks!

**Comment by jokergoo** [comment]
Check this blog post I just wrote: https://jokergoo.github.io/2020/10/29/make-genome-scale-heatmap/

**Comment by ccwang002** [comment]
Great post and elegant design! Thank you so much for your swift reply. I will try out your approach.
