### ISSUE TITLE
gap parameter in gtrellis_layout() overriden when legend present

### ISSUE THREAD

**Issue by adeschen** [jokergoo/gtrellis#5]
Hi,

I would like to create a trellis without gap between chromosomes (`gap=0`) and a legend at the bottom. However, it seems that the `gap=0` is changed to `gap = unit(2, "mm")`, inside the _gtrellis_layout_ function, when a legend is present `(length(legend) > 0)`. 

I wonder if this behavior could be modified. If not, it would be helpful to have this specified in the documentation.

That being said, this package is terrific.

Best,
Astrid

**Comment by jokergoo** [comment]
That was a bug. Now I have fixed it. You can update it from GitHub.

**Comment by adeschen** [comment]
Downloaded and tested. It works great.
Thanks.
